# Generated by Django 5.0.6 on 2024-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Dramat'), (0, 'Inne'), (2, 'Komedia'), (1, 'Horror'), (3, 'Sci-fi')], null=True),
        ),
    ]
