# Generated by Django 5.0.6 on 2024-06-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0005_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imdb_pkts',
            new_name='imdb_points',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (4, 'Dramat'), (3, 'Sci-fi')], null=True),
        ),
    ]
